require("options")
require("keymaps")
require("Lazy")
require("align")
require("autocommands")

-- require("user.lsp")
-- require("user.alpha")
-- require("user.align")
-- require("user.autocommands")
-- require("user.autopairs")
-- require("user.cmp")
-- require("user.comment")
-- require("user.colorscheme")
-- require("user.dap")
-- require("user.gitsigns")
-- require("user.go-nvim")
-- require("user.illuminate")
-- require("user.indentline")
-- require("user.keymaps")
-- require("user.lualine")
-- require("user.minimap")
-- require("user.nvim-tmux-navigation")
-- require("user.nvim-tree")
-- require("user.options")
-- require("user.plugins")
-- require("user.project")
-- require("user.telescope")
-- require("user.toggleterm")
-- require("user.treesitter")
-- require("user.bufferline")
-- require("user.which-key")
